# 3 Creating and presenting stimuli

* 어바웃 파이썬 : 8월 - PsychoPy [1]
* 김무성

# Contents
* Scripts
* The display
* Running scripts
* Timing
* Screens
* Advanced: creating patches Comments

#### 준비단계 
* ../ 폴더의 setup.ipynb 실행한 후

In [24]:
# 현재 디렉토리 확인 
%ls

03_Creating_and_presenting_stimuli.ipynb


In [25]:
# 실습 관련 책의 코드와 데이터
%ls ..

PEP_all-in-one/       all-in-one.zip        hello_psychopy.ipynb
README.md             ch03/                 setup.ipynb


In [28]:
%ls ../PEP_all-in-one/Chapter_03/code/

01_The_display_PsychoPy.zip
01_The_display_PyGaze.zip
02_Screens_PsychoPy.zip
02_Screens_PyGaze.zip
03_Advanced_creating_patches_PsychoPy.zip
03_Advanced_creating_patches_PyGaze.zip


In [29]:
# 실습 파일 가져오자
%cp -r ../PEP_all-in-one/Chapter_03 .

In [30]:
%ls

03_Creating_and_presenting_stimuli.ipynb
Chapter_03/


# Scripts

In [31]:
# 작업 디렉토리 이동 
%cd Chapter_03/code/

/Users/moodern/work/00_aboutpython_psychopy/ch03/Chapter_03/code


In [32]:
%ls

01_The_display_PsychoPy.zip
01_The_display_PyGaze.zip
02_Screens_PsychoPy.zip
02_Screens_PyGaze.zip
03_Advanced_creating_patches_PsychoPy.zip
03_Advanced_creating_patches_PyGaze.zip


In [33]:
# 압축파일을 풀기위한 패키지
import zipfile

In [34]:
all_zip = zipfile.ZipFile('01_The_display_PsychoPy.zip')
all_zip.extractall('./')
all_zip.close()

In [35]:
%ls

01_The_display_PsychoPy/
01_The_display_PsychoPy.zip
01_The_display_PyGaze.zip
02_Screens_PsychoPy.zip
02_Screens_PyGaze.zip
03_Advanced_creating_patches_PsychoPy.zip
03_Advanced_creating_patches_PyGaze.zip


In [36]:
# 작업 디렉토리 이동
%cd 01_The_display_PsychoPy/

/Users/moodern/work/00_aboutpython_psychopy/ch03/Chapter_03/code/01_The_display_PsychoPy


In [37]:
%ls

constants.py   experiment.py


### 실행 방법 1. 
콘솔창을 열어서 
python experiment.py  

### 실행 방법 2.

In [47]:
# 노트북에서 직접 실행
!python experiment.py

1.2270 	WARNING 	Monitor specification not found. Creating a temporary one...
1.2280 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


### 실행 방법 3.

In [75]:
# 직접 노트북에서 
from constants import DISPSIZE
from psychopy.visual import Window
from psychopy.core import wait

# Initialise a new Window instance.
disp = Window(size=DISPSIZE, units='pix', fullscr=True)

# Wait for two seconds.
wait(2)

# Close the Display again.
disp.close()

2438.4803 	WARNING 	Monitor specification not found. Creating a temporary one...
2438.4850 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


# The display

#### Screen Resolution

<code>
PyGaze code
  DISPTYPE = ‘pygame’
  DISPSIZE = (1920, 1080)

PsychoPy code
  DISPSIZE = (1920, 1080)
</code>  

#### Units and colours in PsychoPy Windows

<code>
PyGaze code
  FGC = (0, 0, 0)
  BGC = (128, 128, 128)
  
PsychoPy code
  FGC = (−1, −1, −1)
  BGC = (0, 0, 0)
</code>

#### display 관련

<code>
PyGaze code
  from pygaze.display import Display
    
PsychoPy code
  from psychopy.visual import Window
</code>    

<code>
PyGaze code
  disp = Display()

PsychoPy code
  disp = Window(units='pix', fullscr=True)
</code>    

<code>
PyGaze code
  disp.close()

PsychoPy code
  disp.close()
</code>    

In [76]:
from psychopy.visual import Window

# Initialise a new Window instance.
disp = Window(size=DISPSIZE, units='pix', fullscr=True)

# Close the Display again.
disp.close()

2557.1158 	WARNING 	Monitor specification not found. Creating a temporary one...
2557.1165 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


#### Units and colours in Psychopy Windows

* http://www.psychopy.org/general/colours.html

# Running scripts

### 실습 1 : PyGaze 코드를 실행시켜 보자


In [77]:
# 우선 설치를 해야 한다
# 설치관련 정보 - https://www.pygaze.org/downloads/
!pip install python-pygaze

In [ ]:
# 책에서 제공하는 실습 코드를 실행해보자.


# Timing

<code>
PyGaze code
  import pygaze.libtime as timer

PsychoPy code
  from psychopy.core import wait
</code>    

#### PyGaze code

In [10]:
from pygaze.display import Display
import pygaze.libtime as timer

disp = Display()
timer.pause(2000)

disp.close()

311.7417 	WARNING 	Monitor specification not found. Creating a temporary one...
311.7427 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [800, 600]. Using actual size


#### PsychoPy code

In [51]:
# Window resolution.
DISPSIZE = (1920, 1080)
from psychopy.visual import Window
from psychopy.core import wait

disp = Window(size=DISPSIZE, units='pix', fullscr=True)
wait(2)

disp.close()

695.9739 	WARNING 	Monitor specification not found. Creating a temporary one...
695.9746 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


# Screens

#### draw_fixation

<code>
PyGaze code
  from pygaze.screen import Screen
  fixscreen = Screen()
  fixscreen.draw_fixation(fixtype='dot')
</code>    

In [52]:
from pygaze.display import Display
from pygaze.screen import Screen
import pygaze.libtime as timer

disp = Display()
fixscreen = Screen()
fixscreen.draw_fixation(fixtype='dot')

disp.fill(fixscreen)
disp.show()
timer.pause(2000)
disp.close()

706.6836 	WARNING 	Monitor specification not found. Creating a temporary one...
706.6841 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


<code>
PyschoPy code
  from psychopy.visual import Window, Circle
  disp = Window(units=‘pix’)
  fixmark = Circle(disp, radius=6, edges=64, lineColor=(0,0,0), fillColor=(0,0,0))
</code>

In [53]:
#from constants import DISPSIZE, FGC
DISPSIZE = (1920, 1080)
FGC = (-1, -1, -1)
from psychopy.visual import Window, Circle
from psychopy.core import wait

disp = Window(size=DISPSIZE, units='pix', fullscr=True)

fixmark = Circle(disp, radius=6, edges=64, lineColor=FGC, fillColor=FGC)
fixmark.draw()
disp.flip()
wait(2)

disp.close()

713.4219 	WARNING 	Monitor specification not found. Creating a temporary one...
713.4225 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


#### draw_image

<code>
PyGaze code
  imgscreen = Screen()
  imgscreen.draw_image(‘example.png’)

PsychoPy code
  from psychopy.visual import ImageStim
  disp = Window(units='pix')
  img = ImageStim(disp, image='example.png')
</code>    

##### 준비사항 : exmple.png 파일을 가져와야 한다.

In [54]:
%ls

constants.py   constants.pyc  experiment.py


In [55]:
%ls ..

01_The_display_PsychoPy/
01_The_display_PsychoPy.zip
01_The_display_PyGaze.zip
02_Screens_PsychoPy.zip
02_Screens_PyGaze.zip
03_Advanced_creating_patches_PsychoPy.zip
03_Advanced_creating_patches_PyGaze.zip


In [57]:
%ls ../.. 

code/  files/


In [58]:
%ls ../../files

example.png


In [59]:
%cp ../../files/example.png .

In [60]:
%ls

constants.py   constants.pyc  example.png    experiment.py


In [61]:
# PyGaze code
from pygaze.display import Display
from pygaze.screen import Screen
import pygaze.libtime as timer
  
disp = Display()

fixscreen = Screen()
fixscreen.draw_fixation(fixtype='dot')
  
imgscreen = Screen()
imgscreen.draw_image('example.png')

disp.fill(fixscreen)
disp.show()
timer.pause(1000)
  
disp.fill(imgscreen)
disp.show()
timer.pause(2000)
  
disp.close()

813.7061 	WARNING 	Monitor specification not found. Creating a temporary one...
813.7069 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


### 실습 2 : PsychoPy 코드로 해보자.

In [ ]:
# PsychoPy code


# Advanced: creating patches 

##### Gabor patches

<code>
PsychoPy code
  from psychopy.visual import GratingStim

  gabor = GratingStim(disp, tex='sin', mask='gauss', sf=0.05, size=200)
</code>

<code>
PyGaze code
  import pygaze

  gabor = GratingStim(pygaze.expdisplay, tex=‘sin’, mask=‘gauss’, sf=0.05, size=200) 
  
  gaborscreen = Screen()
  gaborscreen.screen.append(gabor)
</code>

In [62]:
# PyGaze code
import pygaze
from pygaze.display import Display
from pygaze.screen import Screen
import pygaze.libtime as timer
from psychopy.visual import GratingStim

disp = Display()

gabor = GratingStim(pygaze.expdisplay, tex='sin', mask='gauss', sf=0.05, size=200)

gaborscreen = Screen()
gaborscreen.screen.append(gabor)
disp.fill(gaborscreen)

disp.show()
timer.pause(1000)

disp.close()

829.5197 	WARNING 	Monitor specification not found. Creating a temporary one...
829.5205 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


### 실습 3 : PsychoPy 코드로 해보자.

In [ ]:
# PsychoPy code


##### Noise

In [63]:
import numpy
  
noise = numpy.random.rand(64, 64)

In [64]:
noise

array([[ 0.56946684,  0.40807112,  0.84505911, ...,  0.58445719,
         0.46118323,  0.46395101],
       [ 0.24439546,  0.60208159,  0.50004928, ...,  0.42075098,
         0.95291426,  0.71906069],
       [ 0.58481643,  0.10573734,  0.08032324, ...,  0.77565376,
         0.86821764,  0.36985903],
       ..., 
       [ 0.72978864,  0.29291466,  0.39647248, ...,  0.89991858,
         0.88119404,  0.39437347],
       [ 0.83865162,  0.7093679 ,  0.22628574, ...,  0.86120281,
         0.0786899 ,  0.71200879],
       [ 0.72605052,  0.98882426,  0.52424013, ...,  0.75986916,
         0.60807643,  0.0357842 ]])

In [65]:
noise = numpy.random.rand(64, 64) * 2

In [66]:
noise

array([[ 1.1765327 ,  0.51381834,  1.39351641, ...,  0.90352603,
         0.30337291,  1.92555664],
       [ 0.28309903,  1.58670316,  0.48831233, ...,  0.63612008,
         1.75318189,  1.93679016],
       [ 1.2366536 ,  0.26917647,  0.43003174, ...,  0.53210494,
         0.55540163,  0.24919941],
       ..., 
       [ 1.71267221,  1.63954634,  1.6493295 , ...,  1.25422456,
         1.99347727,  0.90305187],
       [ 1.84928958,  0.48673107,  0.32467519, ...,  1.87691304,
         0.76055563,  0.91800361],
       [ 1.07517415,  1.63443245,  0.2589242 , ...,  0.26812303,
         1.09558727,  0.49524529]])

In [67]:
noise = (numpy.random.rand(64, 64) * 2) - 1

In [68]:
noise

array([[  4.87405101e-02,  -7.28169785e-01,   8.65038255e-01, ...,
         -2.96298751e-01,   3.61120898e-03,  -2.09734390e-02],
       [ -7.48114580e-01,   7.40694059e-01,   6.44070133e-01, ...,
         -6.39018129e-01,  -6.86925814e-01,  -2.52432924e-01],
       [ -4.03827350e-01,   1.91012405e-01,  -6.59217241e-01, ...,
          8.26781130e-04,  -9.84211663e-01,   6.45420744e-01],
       ..., 
       [ -6.83019365e-01,  -1.46395218e-01,   6.81918921e-01, ...,
          1.95939010e-03,  -2.30684457e-01,  -5.71821999e-01],
       [  9.53698614e-01,   1.68888827e-01,   2.10352311e-01, ...,
          5.79401179e-01,  -4.40517376e-01,  -3.22723276e-01],
       [  3.85611925e-01,  -2.10170560e-01,  -6.91269494e-01, ...,
          6.19413468e-02,   3.70880227e-01,   4.48423463e-01]])

<code>
PyGaze code
  import pygaze
  from psychopy.visual import GratingStim
  noisepatch = GratingStim(pygaze.expdisplay, tex=noise, mask=‘gauss’, size=200)
</code>

In [69]:
# PyGaze code
import pygaze
from pygaze.display import Display
from pygaze.screen import Screen
import pygaze.libtime as timer
from psychopy.visual import GratingStim

disp = Display()

gabor = GratingStim(pygaze.expdisplay, tex='sin', mask='gauss', sf=0.05, size=200)
gaborscreen = Screen()
gaborscreen.screen.append(gabor)

noisepatch = GratingStim(pygaze.expdisplay, tex=noise, mask='gauss', sf=0.05, size=200)
noisescreen = Screen()
noisescreen.screen.append(noisepatch)

disp.fill(gaborscreen)
disp.show()
timer.pause(1000)
  
disp.fill(noisescreen)
disp.show()
timer.pause(2000)

disp.close()

848.5187 	WARNING 	Monitor specification not found. Creating a temporary one...
848.5194 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


### 실습 4 : PsychoPy 코드로 해보자.

In [ ]:
# PsychoPy code


# Comments

In [71]:
import pygaze
from pygaze.display import Display
from pygaze.screen import Screen
import pygaze.libtime as timer
import numpy
from psychopy.visual import GratingStim

# Initialise a new Display instance (specifications are in
# constants.py).
disp = Display()

# Create a new GratingStim. The sinusoidal texture and the
# Gaussian mask will make it into a Gabor. The spatial
# frequency of 0.05 cycles per pixel will make it have
# 1 cycle every 20 pixels.
gabor = GratingStim(pygaze.expdisplay, tex='sin', mask='gauss', sf=0.05, size=200)

# Initialise a new Screen instance for the Gabor.
gaborscreen = Screen()
# Add the GratingStim to the gaborscreen’s screen property
# (a list of all PsychoPy stimuli in the Screen).
gaborscreen.screen.append(gabor)

# Create random numbers between 0 and 1 (numpy.random.
# rand), converted to numbers between 0 and 2 (*2), and
# then converted to numbers between −1 and 1 (−1). The size
# must be a power of 2!
noise = (numpy.random.rand(64, 64) * 2) - 1

# Create a new GratingStim. Using the noise array as
# texture will result in visual snow. The mask is Gaussian
# (to match the Gabor).
noisepatch = GratingStim(pygaze.expdisplay, tex=noise, mask='gauss', size=200)

# Initialise a new Screen instance for the noise.
noisescreen = Screen()

# Add the GratingStim to the Screen’s screen property (as
# with Gabor).
noisescreen.screen.append(noisepatch)

# Fill the Display with the Gabor Screen that was prepared
# earlier.
disp.fill(gaborscreen)

# Present the Display (Gabor will now be on the monitor).
disp.show()

# Wait for 1000 milliseconds (Gabor is still on the
# monitor).
timer.pause(1000)

# Fill the Display with the noise Screen that was prepared
# earlier.
disp.fill(noisescreen)

# Present the Display (noise is now on the monitor).
disp.show()

# Wait 2000 milliseconds (noise is still on the monitor).
timer.pause(2000)

# Close the Display (this will end the experiment).
disp.close()

891.4772 	WARNING 	Monitor specification not found. Creating a temporary one...
891.4778 	WARNING 	User requested fullscreen with size [1920 1080], but screen is actually [1280, 800]. Using actual size


# 참고자료
* [1] Python for Experimental Psychologists - https://www.amazon.com/Python-Experimental-Psychologists-Edwin-Dalmaijer/dp/1138671576
* [2] 책 정보 & 코드 - http://www.pygaze.org/pep/
* [3] 코드 한번에 받기 - http://www.pygaze.org/resources/downloads/PEP/all-in-one.zip
    